name: PEP 8 Check

on:
  push:
    branches:
      - main
    paths:
        - 'src/**'
        - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
        - 'src/**'
        - 'tests/**'
jobs:
  pep8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'
          cache: 'pip' # Caches dependencies to speed up workflow runs

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 --config .flake8 .
